version: "2"

services:
  app:
    build: .
    image: mong0520/linebot-ptt-beauty:latest
    env_file: .env
    volumes:
      - ./ssl:/ssl
    ports:
      - 443:443
    depends_on:
      - db

  db:
    image: mongo
    volumes:
      - ./db/volume:/data/db
    ports:
      - 27017:27017
